
export const images = {
    Aa: require('./assets/pictures/A.png'),
    Bb: require('./assets/pictures/B.png'),
    Cc: require('./assets/pictures/C.png'),
    Dd: require('./assets/pictures/D.png'),
    Ee: require('./assets/pictures/E.png'),
    Ff: require('./assets/pictures/F.png'),
    Gg: require('./assets/pictures/G.png'),
    Hh: require('./assets/pictures/H.png'),
    Ii: require('./assets/pictures/I.png'),
    Jj: require('./assets/pictures/J.png'),
    Kk: require('./assets/pictures/K.png'),
    Ll: require('./assets/pictures/L.png'),
    Mm: require('./assets/pictures/M.png'),
    Nn: require('./assets/pictures/N.png'),
    Oo: require('./assets/pictures/O.png'),
    Pp: require('./assets/pictures/P.png'),
    Qq: require('./assets/pictures/Q.png'),
    Rr: require('./assets/pictures/R.png'),
    Ss: require('./assets/pictures/S.png'),
    Tt: require('./assets/pictures/T.jpg'),
    Uu: require('./assets/pictures/U.png'),
    Vv: require('./assets/pictures/V.png'),
    Ww: require('./assets/pictures/W.png'),
    Xx: require('./assets/pictures/X.png'),
    Yy: require('./assets/pictures/Y.png'),
    Zz: require('./assets/pictures/Z.png'),
};

export const alphabetArray = [
    'Aa',
    'Bb',
    'Cc',
    'Dd',
    'Ee',
    'Ff',
    'Gg',
    'Hh',
    'Ii',
    'Jj',
    'Kk',
    'Ll',
    'Mm',
    'Nn',
    'Oo',
    'Pp',
    'Qq',
    'Rr',
    'Ss',
    'Tt',
    'Uu',
    'Vv',
    'Ww',
    'Xx',
    'Yy',
    'Zz',
];

export const videoPath = {
    Aa: require('./assets/video/A.mp4'),
    Bb: require('./assets/video/B.mp4'),
    Cc: require('./assets/video/C.mp4'),
    Dd: require('./assets/video/D.mp4'),
    Ee: require('./assets/video/E.mp4'),
    Ff: require('./assets/video/F.mp4'),
    Gg: require('./assets/video/G.mp4'),
    Hh: require('./assets/video/H.mp4'),
    Ii: require('./assets/video/I.mp4'),
    Jj: require('./assets/video/J.mp4'),
    Kk: require('./assets/video/K.mp4'),
    Ll: require('./assets/video/L.mp4'),
    Mm: require('./assets/video/M.mp4'),
    Nn: require('./assets/video/N.mp4'),
    Oo: require('./assets/video/O.mp4'),
    Pp: require('./assets/video/P.mp4'),
    Qq: require('./assets/video/Q.mp4'),
    Rr: require('./assets/video/R.mp4'),
    Ss: require('./assets/video/S.mp4'),
    Tt: require('./assets/video/T.mp4'),
    Uu: require('./assets/video/U.mp4'),
    Vv: require('./assets/video/V.mp4'),
    Ww: require('./assets/video/W.mp4'),
    Xx: require('./assets/video/X.mp4'),
    Yy: require('./assets/video/Y.mp4'),
    Zz: require('./assets/video/Z.mp4'),
};

export const audioPath = {
    Aa: require('./assets/audio/a.mp3'),
    Bb: require('./assets/audio/b.mp3'),
    Cc: require('./assets/audio/c.mp3'),
    Dd: require('./assets/audio/d.mp3'),
    Ee: require('./assets/audio/e.mp3'),
    Ff: require('./assets/audio/f.mp3'),
    Gg: require('./assets/audio/g.mp3'),
    Hh: require('./assets/audio/h.mp3'),
    Ii: require('./assets/audio/i.mp3'),
    Jj: require('./assets/audio/j.mp3'),
    Kk: require('./assets/audio/k.mp3'),
    Ll: require('./assets/audio/l.mp3'),
    Mm: require('./assets/audio/m.mp3'),
    Nn: require('./assets/audio/n.mp3'),
    Oo: require('./assets/audio/o.mp3'),
    Pp: require('./assets/audio/p.mp3'),
    Qq: require('./assets/audio/q.mp3'),
    Rr: require('./assets/audio/r.mp3'),
    Ss: require('./assets/audio/s.mp3'),
    Tt: require('./assets/audio/t.mp3'),
    Uu: require('./assets/audio/u.mp3'),
    Vv: require('./assets/audio/v.mp3'),
    Ww: require('./assets/audio/w.mp3'),
    Xx: require('./assets/audio/x.mp3'),
    Yy: require('./assets/audio/y.mp3'),
    Zz: require('./assets/audio/z.mp3'),
};