
export const images = {
    A: require('./assets/pictures/A.png'),
    B: require('./assets/pictures/B.png'),
    C: require('./assets/pictures/C.png'),
    D: require('./assets/pictures/D.png'),
    E: require('./assets/pictures/E.png'),
    F: require('./assets/pictures/F.png'),
    G: require('./assets/pictures/G.png'),
    H: require('./assets/pictures/H.png'),
    I: require('./assets/pictures/I.png'),
    J: require('./assets/pictures/J.png'),
    K: require('./assets/pictures/K.png'),
    L: require('./assets/pictures/L.png'),
    M: require('./assets/pictures/M.png'),
    N: require('./assets/pictures/N.png'),
    O: require('./assets/pictures/O.png'),
    P: require('./assets/pictures/P.png'),
    Q: require('./assets/pictures/Q.png'),
    R: require('./assets/pictures/R.png'),
    S: require('./assets/pictures/S.png'),
    T: require('./assets/pictures/T.jpg'),
    U: require('./assets/pictures/U.png'),
    V: require('./assets/pictures/V.png'),
    W: require('./assets/pictures/W.png'),
    X: require('./assets/pictures/X.png'),
    Y: require('./assets/pictures/Y.png'),
    Z: require('./assets/pictures/Z.png'),
};

export const alphabetArray = [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
];

export const videoPath = {
    A: require('./assets/video/A.mp4'),
    B: require('./assets/video/B.mp4'),
    C: require('./assets/video/C.mp4'),
    D: require('./assets/video/D.mp4'),
    E: require('./assets/video/E.mp4'),
    F: require('./assets/video/F.mp4'),
    G: require('./assets/video/G.mp4'),
    H: require('./assets/video/H.mp4'),
    I: require('./assets/video/I.mp4'),
    J: require('./assets/video/J.mp4'),
    K: require('./assets/video/K.mp4'),
    L: require('./assets/video/L.mp4'),
    M: require('./assets/video/M.mp4'),
    N: require('./assets/video/N.mp4'),
    O: require('./assets/video/O.mp4'),
    P: require('./assets/video/P.mp4'),
    Q: require('./assets/video/Q.mp4'),
    R: require('./assets/video/R.mp4'),
    S: require('./assets/video/S.mp4'),
    T: require('./assets/video/T.mp4'),
    U: require('./assets/video/U.mp4'),
    V: require('./assets/video/V.mp4'),
    W: require('./assets/video/W.mp4'),
    X: require('./assets/video/X.mp4'),
    Y: require('./assets/video/Y.mp4'),
    Z: require('./assets/video/Z.mp4'),
};

export const audioPath = {
    A: require('./assets/audio/a.mp3'),
    B: require('./assets/audio/b.mp3'),
    C: require('./assets/audio/c.mp3'),
    D: require('./assets/audio/d.mp3'),
    E: require('./assets/audio/e.mp3'),
    F: require('./assets/audio/f.mp3'),
    G: require('./assets/audio/g.mp3'),
    H: require('./assets/audio/h.mp3'),
    I: require('./assets/audio/i.mp3'),
    J: require('./assets/audio/j.mp3'),
    K: require('./assets/audio/k.mp3'),
    L: require('./assets/audio/l.mp3'),
    M: require('./assets/audio/m.mp3'),
    N: require('./assets/audio/n.mp3'),
    O: require('./assets/audio/o.mp3'),
    P: require('./assets/audio/p.mp3'),
    Q: require('./assets/audio/q.mp3'),
    R: require('./assets/audio/r.mp3'),
    S: require('./assets/audio/s.mp3'),
    T: require('./assets/audio/t.mp3'),
    U: require('./assets/audio/u.mp3'),
    V: require('./assets/audio/v.mp3'),
    W: require('./assets/audio/w.mp3'),
    X: require('./assets/audio/x.mp3'),
    Y: require('./assets/audio/y.mp3'),
    Z: require('./assets/audio/z.mp3'),
};